### ISSUE TITLE
lint/param-duplcaion: check also return types

### ISSUE THREAD

**Issue by fexolm** [PieselBois/kfulint#105]
Right now param-duplication checker check only functuion param types. It should also check return type.
Also, when someone will finish that task be sure to rename checker.

**Comment by Quasilyte** [comment]
Just a note: it does check return types in updated version since it's re-written in terms of "param list checker" which handles all parameters (receiver, inputs and outputs).
I'll try to send that in near time.

**Comment by Quasilyte** [comment]
Fixed in #109.
