### ISSUE TITLE
docs: add step-by-step guide that describes how to add new checker

### ISSUE THREAD

**Issue by Quasilyte** [PieselBois/kfulint#116]
In short, the process is like:

1. Come up with checker idea. Concentrate on *what it checks*.
2. Select one of the base checkers kind (example: expr checker, stmt checker, etc.).
3. Define checker type and constructor function.
4. Add entry to checkers list in `lint.go`. It could be a good idea to mark recently added checker as `experimental`.
5. Add test directory that is named after the checker in `cmd/kfulint/testdata`.
6. Add `checker_tests.go` file in that directory and add some positive and negative tests there.
7. Run tests. They must fail as your checker does not check anything yet. Tests can be run with 
`go test -v github.com/PieselBois/kfulint/cmd/kfulint`.
8. Implement checker itself. Make tests pass.

**Comment by weeellz** [comment]
@Quasilyte, where should this guide be? In contributing.md or in separate file?

**Comment by Quasilyte** [comment]
Tough question.
I think either way is fine.
As soon as we get good content it will be trivial to move it around.

By the way, are you OK with `org` files?
Does your editor support them?

**Comment by Quasilyte** [comment]
I suggest assigning @tengufromsky for this doc review.
He can check if it can be understood by someone who is not very familiar with our project.

**Comment by weeellz** [comment]
@Quasilyte, yup, `org` files is ok.
