### ISSUE TITLE
lint/type-guard_checker.go: fix misspell warning 

### ISSUE THREAD

**Issue by fexolm** [PieselBois/kfulint#30]
Line 62: warning: "artifical" is a misspelling of "artificial" (misspell)

**Comment by Quasilyte** [comment]
Damn. Overlooked this one.

This is a location:
https://github.com/PieselBois/kfulint/blob/45a96356ddc728d7efd43c55fc8fec924875dade/lint/type-guard_checker.go#L62

**Comment by fexolm** [comment]
fixed in  #33
