### ISSUE TITLE
all: fix linter warnings

### ISSUE THREAD

**Issue by weeellz** [PieselBois/kfulint#40]
`cmd/kfulint/main.go:47:12:warning: parameter format always receives "Illegal empty -dir argument\n" (unparam)`
`lint/parenthesis-checker.go:70::warning: line is 116 characters (lll)`
`lint/type-guard_checker.go:21::warning: line is 81 characters (lll)`
`lint/type-guard_checker.go:89::warning: line is 83 characters (lll)`
`lint/type-guard_checker.go:101::warning: line is 87 characters (lll)`
`lint/internal/astfilter/astfilter.go:1::warning: line is 84 characters (lll)`

**Comment by Quasilyte** [comment]
I think we should disable both of these checks.
Especially `lll`. I would disable it 3 times.

`unparam` is a refactor driver, not a good CI checker.

**Comment by Quasilyte** [comment]
Seems like this can be done as a part of #32.

**Comment by weeellz** [comment]
Ok. Done in #41.
