### ISSUE TITLE
lint/parenthesis_checker.go: add support for types 

### ISSUE THREAD

**Issue by fexolm** [PieselBois/kfulint#47]
we neet to add support for types, declareted like so:
`type a (int)` ===>> `type a int`

**Comment by Quasilyte** [comment]
Hey, that's not type aliases. :)
Go have "real" type aliases, and they look like this:
```go
type a = b
```
https://golang.org/ref/spec#Alias_declarations

**Comment by fexolm** [comment]
Oh, my mistake.
