### ISSUE TITLE
cmd/kfulint: improve test coverage for checkers

### ISSUE THREAD

**Issue by Quasilyte** [PieselBois/kfulint#52]
Please consider adding more corner cases for checkers.
One that can potentially cause panic or are not working/detectable yet are especially useful.

This is important to do it before we get too much untested checkers.
So, **let's not implement anything outside of [v0.1](https://github.com/PieselBois/kfulint/milestone/1) milestone until we're finished with this**.
This will be a closing issue for v0.1 when everything else is completed.

This issue should be referenced from every related commit.

**Comment by Quasilyte** [comment]
We also need to test every existing linter on big codebase, like Go core distribution.

We don't have tools for that right now, but we want to detect potential panics/crashes in our code that happens when running checkers over real code.

**Comment by fexolm** [comment]
@Quasilyte, should we add #41 -#47 to v0.1?

**Comment by Quasilyte** [comment]
@fexolm, we can concentrate on improvement of existing checkers and their correctness.
The correctness is a priority for v0.1.
It's OK to do partial analysis, but it's bad to panic on valid Go code, for example.
False positives are also unwanted.

I also think that we should move #13 to v0.2.
Most likely, we'll hit enter v0.2 in a few days, depends on how many fatal errors we can find during testing and fuzz-like experimenting.

**Comment by Quasilyte** [comment]
Note that v0.1 is not a release.
We'll use semantic versioning for releases, but I don't have a good idea for milestone names.
They're currently used like "sprints" in this project.
