### ISSUE TITLE
cmd/kfulint: add sanity checks

### ISSUE THREAD

**Issue by Quasilyte** [PieselBois/kfulint#57]
Every linter must be properly handle files that may contain unexpected input.
For example:
```go
func external() // Function with nil body

func empty() {} // Function without input/output params and empty body

// Empty value/type specs:
var ()
const ()
type ()
```

And so on.

**Comment by fexolm** [comment]
It looks easy. Maybe mark it as good first issue?

**Comment by fexolm** [comment]
Also, I think other linter would find that.

**Comment by Quasilyte** [comment]
It's not a suggestion for checker, it's extension to our end2end tests.
We don't want our checkers to panic on such constructs just because we forgot about some corner case.
