### ISSUE TITLE
lint: parenthesis suggests to simplify size expressions inside array types

### ISSUE THREAD

**Issue by Quasilyte** [PieselBois/kfulint#60]
```
cmd/internal/obj/x86/asm6.go:2043:14: parenthesis: could simplify (ALAST + 1) to ALAST + 1
```

`[(A + B)]int` is an array of ints with size `A+B`. 
Expressions can be complex and it's not quite right to trigger on them.

I don't remember any other cases except for array types, so maybe all what is required is to avoid array type length checks.

```go
	ArrayType struct {
		Lbrack token.Pos // position of "["
		Len    Expr      // Ellipsis node for [...]T array types, nil for slice types
		Elt    Expr      // element type
	}
```

`parenthesis` should not visit `ArrayType.Len`.

**Comment by Quasilyte** [comment]
Not urgent.

**Comment by fexolm** [comment]
@Quasilyte, it might be useful to trigger on expressions like [(A + B)]int, but not like [(A + B) + C]int
