### ISSUE TITLE
lint: add type switch -> if suggestions for 1-case statements

### ISSUE THREAD

**Issue by Quasilyte** [PieselBois/kfulint#70]
If type switch has only 1 case, it can be replaced with if statement.

This code triggers a warning:
```go
func intValue(x interface{}) int {
	switch x := x.(type) {
	case int:
		return x
	}
	return 0
}
```

Suggested alternative:
```go
func intValueSuggested(x interface{}) int {
	if x, ok := x.(int); ok {
		return x
	}
	return 0
}
```

**Comment by Quasilyte** [comment]
We'll try to address this checker on our next meeting.
@fexolm, what do you think about pair programming for this checker with @weeellz?

**Comment by weeellz** [comment]
Done in #101.
