### ISSUE TITLE
lint: add unnecessary brackets checker

### ISSUE THREAD

**Issue by fexolm** [PieselBois/kfulint#9]
We need to add checker which will find the errors described below.
 - [x] `var _ [n](*int)` ===>> `var _ [n]*int`
 - [x] `*(name).field` ===>> `name.field` (moved to #14.)
 - [x] `var _ (func())` ===>> `var _ func()`
 - [x] `func(...) (...)` ===>> `func(...) ...`
 - [x] `(*a)[i]` where a is an array (moved to #14.)

**Comment by Quasilyte** [comment]
You can start with a simplest case: fix function result types.
This way, you can concentrate on parenthesis elimination instead of type expression seeking.
Then you can expand the scope to more type expressions.

**Comment by Quasilyte** [comment]
There is also `(*a)[i]` where `a` is an array (not a slice).

**Comment by Quasilyte** [comment]
Do we need [astutil](https://godoc.org/golang.org/x/tools/go/ast/astutil)?
https://github.com/golang/tools/blob/master/go/ast/astutil/util.go#L6

**Comment by fexolm** [comment]
Function return statement case is done in #22.

**Comment by fexolm** [comment]
Checks 2 and 5 moved to #14.
